services:
  - type: web
    plan: free
    runtime: docker
    name: imob-back
    repo: https://github.com/devalvesg/microservice-imobiliaria # Default: Repo containing render.yaml
    healthCheckPath: /
    dockerfilePath: ./imob-back
  - type: web
    runtime: docker
    plan: free
    name: email-sending
    repo: https://github.com/devalvesg/microservice-imobiliaria # Default: Repo containing render.yaml
    healthCheckPath: /
    dockerfilePath: ./email-sending

